spring.datasource.url=jdbc:postgresql://dpg-d76uo8f5r7bs73e24q60-a.singapore-postgres.render.com:5432/db1_3o1k
spring.datasource.username=db1_3o1k_user
spring.datasource.password=yiG76bzpoJZabqEoUxWKQVaaXphM4lnd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

server.id=1